# Generated by Django 4.2.1 on 2023-05-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=150)),
                ('linenos', models.BooleanField()),
                ('language', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='sinppet',
        ),
    ]
